language: node_js
notifications:
email: ythalorossy@gmail.com
node_js:
  - 0.10
services:
  - mongodb
env:
  global:
    - NODE_ENV: test
addons:
  sauce_conn ect: true
before_inst all:
  - npm install -g bower@1 .3
  - npm install -g grunt-c li@0.1
  - npm install -g karma-c li@0.0
  - npm install -g protrac tor@1.5
  - webdriver-ma nager update
  - bower install
before_scri pt:
  - node test/data. js
  - grunt
  - cd dist
script:
  - karma start config/ karma.config.js --singl e-run --browsers PhantomJS
  - node server &
  - protractor conf ig/protractor.js